# These substitutions allow the end user to override certain values
substitutions:
  # Device Names
  name: "localbytes-plug-pm"
  friendly_name: "Localbytes Plug PM"
  main_icon: "power-socket-uk"
  ota_key: "qwertyuiop"
  api_key: "qwertyuiop"
  wifi_ssid: "wifi"
  wifi_password: "password"
  ap_ssid: "Smart-Plug Fallback Hotspot"
  app: "Smart-Plug Fallback Hotspot Password"
  name_add_mac_suffix: "true"

  # Default Relay State
  # Aka: `restore_mode` in documentation
  # Options: `RESTORE_DEFAULT_OFF`, `RESTORE_DEFAULT_ON`, `ALWAYS_ON` & `ALWAYS_OFF`
  default_state: "RESTORE_DEFAULT_OFF"

  # Default state of the "disable led" virtual switch 
  disable_led_default_state: "RESTORE_DEFAULT_OFF"

  # Default state of the "disable button"/child-lock virtual switch
  disable_button_default_state: "RESTORE_DEFAULT_OFF"  

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: ${name_add_mac_suffix}

  project:
    name: avt613.esphome-smart-plug
    version: "1.8.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

logger:

ota:
  - platform: esphome
    password: "${ota_key}"
api:
  encryption:
    key: "${api_key}"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://avt613/esphome-smart-plug/localbytes-plug-pm.yaml@main

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${ap_ssid}"
    password: "${ap_password}"

captive_portal:
